### ISSUE TITLE
Ability to add headers when redirecting

### ISSUE THREAD

**Issue by DullReferenceException** [godaddy/node-redirect-rules#1]
Suggestion from @gingur was to allow adding extra headers when redirecting, like `x-forward`, `x-redirected-from`, etc.

**Comment by apoco** [comment]
@gingur, good suggestion. Could you look at  this pull request? It lets you set both headers and a body when redirecting: https://github.com/godaddy/node-redirect-rules/pull/5

**Comment by DullReferenceException** [comment]
Fixed by #5
